# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_text', models.CharField(max_length=40)),
                ('start_date', models.DateTimeField(verbose_name='Conference Start Date')),
                ('end_date', models.DateTimeField(verbose_name='Conference End Date')),
            ],
        ),
    ]
