# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='end_date',
            field=models.DateField(verbose_name='Conference End Date'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='start_date',
            field=models.DateField(verbose_name='Conference Start Date'),
        ),
    ]
