# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
        ('presentations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='conference',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='conferences.Conference'),
            preserve_default=False,
        ),
    ]
